# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Her 12 saatte bir
    - cron: "0 */12 * * *"

  # Actions sekmesinden manuel olarak çalıştırılmasını sağlar.
  workflow_dispatch:
  
  # Ayrıca, her itişte çalışır.
  push:
    branches:
      - main

# Bu iş akışındaki çalışma dizisinin sıralaması:
jobs:
  # Bu iş akışı, "build" adında tek bir işe sahiptir.
  build:
    # İşin çalıştığı runner tipi
    runs-on: ubuntu-latest

    # Adımlar, işin bir parçası olarak yürütülecek görev dizisini temsil eder.
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: KayaErtug
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
